Support menu's nocheckmark attribute
AlaskaAirlines/auro-select pull request #100
Opened 2022-09-09 17:24 UTC by jordanjones243

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #88 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

Added support for auro-menu's `nocheckmark` attribute, while making checkmark in select the default.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-09-09 21:51 UTC, blackfalcon requested changes

2022-09-09 21:51 UTC, blackfalcon commented on docs/partials/demo.md
> +### Example with no checkmark
Why is the following example missing? 

```
### Example with nested menus

<div class="exampleWrapper">
  <!-- AURO-GENERATED-CONTENT:START (FILE:src=./../../apiExamples/withSubmenus.html) -->
  <!-- AURO-GENERATED-CONTENT:END -->
</div>

<auro-accordion lowProfile justifyRight>
  <span slot="trigger">See code</span>

<!-- AURO-GENERATED-CONTENT:START (CODE:src=./../../apiExamples/withSubmenus.html) -->
<!-- AURO-GENERATED-CONTENT:END -->

</auro-accordion>
```

2022-09-09 21:51 UTC, blackfalcon commented on docs/partials/demo.md
> +
Missed closing `</auro-accordion>`. The demo page UI breaks when rendered locally.

2022-09-09 21:51 UTC, blackfalcon commented on src/auro-select.js
> + * @prop {Boolean} checkmark - When true, selected option will show the checkmark.
This is incorrect. The default should be with the checkmark and the new feature is to remove the checkmark. Update this feature to be `noCheckmark`.

2022-09-12 18:56 UTC, jordanjones243 commented
New PR created after merge conflict mess: https://github.com/AlaskaAirlines/auro-select/pull/103

2022-09-12 18:56 UTC, closed without merging