Update CSS token per new design system theming capability
AlaskaAirlines/auro-select pull request #164
Opened 2023-10-20 12:13 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

**Fixes:** #163 

## Summary:

- Update the design tokens to reflect the new theming conventions regarding tokens from the AuroDesignTokens and JetstreamDesignTokens repo.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-10-20 12:15 UTC, fajar-apri-alaska commented
The  `npm ci` is failing because some auro components have conflicting peer dependency for `@aurodesignsystem/webcorestylesheets` package. Should I hold of this until those components are updated?

2023-10-20 12:21 UTC, fajar-apri-alaska commented
Also bumping `auro-dropdown` version to 2.9.9 as a temporary solution for this PR, because somehow the run test are failing from the `auro-dropdown` version in main branch (2.9.6)

2023-11-01 20:27 UTC, jason-capsule42 requested changes

2023-11-01 20:27 UTC, jason-capsule42 commented on src/style.scss
> +        background-color: var(--ds-color-ui-bkg-hover-default);
Add the fallback value

2023-11-02 03:36 UTC, fajar-apri-alaska commented on src/style.scss
> +        background-color: var(--ds-color-ui-bkg-hover-default);
My bad, thanks for noticing.

2023-11-02 15:52 UTC, jason-capsule42 approved these changes

2023-11-02 15:52 UTC, merged

2023-11-02 15:55 UTC, blackfalcon commented
:tada: This PR is included in version 2.8.5 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-select/v/2.8.5)
- [GitHub release](https://github.com/AlaskaAirlines/auro-select/releases/tag/v2.8.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: