fix: handle long value option
AlaskaAirlines/auro-select pull request #188
Opened 2024-05-21 01:55 UTC by ipin-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** # (issue, if applicable)

## Summary:

- This PR is to fix the issue on auro-menu https://github.com/AlaskaAirlines/auro-menu/issues/165
- Adding `position: relative` to the `auro-dropdown` host
- Adding `max-width: -webkit-fill-available` to the `auro-dropdown` popover wrapper

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-05-28 19:45 UTC, jason-capsule42 requested changes
This change is in the wrong component. The fix should be in auro-menu to do truncation with elipsis when the auro-menuoption slot content is too long to fit in the rendered width.

2024-05-29 08:45 UTC, ipin-alaska commented
> This change is in the wrong component. The fix should be in auro-menu to do truncation with elipsis when the auro-menuoption slot content is too long to fit in the rendered width.

Hi @jason-capsule42, thank you for your feedback. Actually `auro-menu` component already handled long values with ellipsis styling as you can see below example.

<img width="1440" alt="Screenshot 2024-05-29 at 14 45 02" src="https://github.com/AlaskaAirlines/auro-select/assets/169977075/443fd427-4990-42e9-b35d-d5a2d6dbd044">

The problem is on the wrapper of that `auro-menu` which is the popover class. So I think we need to set `max-width` on it. Please let me know if you have another concern. Thanks

2024-05-30 04:35 UTC, jason-capsule42 approved these changes

2024-05-30 04:35 UTC, merged

2024-05-30 04:38 UTC, blackfalcon commented
:tada: This PR is included in version 2.10.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-select/v/2.10.3)
- [GitHub release](https://github.com/AlaskaAirlines/auro-select/releases/tag/v2.10.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: