fix(demo): fix js files for extracting value in demo #55
AlaskaAirlines/auro-select pull request #56
Opened 2022-03-28 22:02 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #55

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**
-- Auro Design System Team

2022-03-28 22:31 UTC, blackfalcon requested changes
I updated the comment to be `docs` as there is no need for a version release. This util is not used as a feature, but for the demos. 

I also added back the demo that was removed because this wasn't working. It working, but not working... see screenshot. When an option is selected the alert pops up without any other action. 

<img width="1114" alt="Screen Shot 2022-03-28 at 3 28 12 PM" src="https://user-images.githubusercontent.com/181089/160497720-ecea2d5d-785f-469b-a789-f01b9aec26b1.png">

2022-03-29 16:23 UTC, jason-capsule42 commented
Issue you were seeing @blackfalcon is resolved - the alertValue.js and extractValue.js were both being applied to the same example. Adding in the second demo meant it had no functional event listener for the value change attached. I pointed alertValue.js to it.

2022-03-29 16:34 UTC, blackfalcon approved these changes

2022-03-29 17:46 UTC, blackfalcon approved these changes

2022-03-29 18:52 UTC, merged

2022-03-29 18:56 UTC, blackfalcon commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-select/v/2.2.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-select/releases/tag/v2.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: