feat(API): add ready state checks and all automated tests #38 #75
AlaskaAirlines/auro-select pull request #80
Opened 2022-07-26 02:39 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #38, #75

## Summary:

Adds the ready check behavior for peer dependencies and all automated testing to pass threshold requirements.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-07-29 21:25 UTC, blackfalcon requested changes
I would have preferred that the different updates were kept in individual commits, e.g. tests versus features. 

Other than that, please update the JSDoc comments are you are good to go.

2022-07-29 21:25 UTC, blackfalcon commented on src/auro-select.js
> +   */
Please follow the preferred JSDoc pattern. 

```
  /**
   * Marks the component as ready and sends event.
   * @private
   * @returns {void} 
   */
```

2022-07-29 21:25 UTC, blackfalcon commented on src/auro-select.js
> +   */
Please add the appropriate contextual information for this comment header.

2022-08-03 17:21 UTC, MattSidor approved these changes

2022-08-03 18:33 UTC, merged

2022-08-03 18:36 UTC, blackfalcon commented
:tada: This PR is included in version 2.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-select/v/2.4.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-select/releases/tag/v2.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: